name: Run Cypress Login Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "INSURANCE_USER=\${{ secrets.INSURANCE_USER }}" >> .env
          echo "INSURANCE_PASS=\${{ secrets.INSURANCE_PASS }}" >> .env

      - name: Run Login Spec
        run: npx cypress run --spec "cypress/integration/login/login-flow.spec.js"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports/html
